finish
Luciaw1219/FarmerFroilan pull request #16
Opened 2023-05-21 23:23 UTC by mouad1937

2023-05-21 23:25 UTC, Amineiscool submitted a review, later dismissed

2023-05-22 00:08 UTC, Luciaw1219 requested changes

2023-05-22 00:08 UTC, Luciaw1219 commented on src/main/java/com/zipcodewilmington/froilansfarm/plants/Crop.java
i dont think any of these methods you added are neccessary

2023-05-22 00:08 UTC, Luciaw1219 commented on src/main/java/com/zipcodewilmington/froilansfarm/plants/Tomato.java
this class already exists in the food package

2023-05-22 01:10 UTC, Luciaw1219 approved these changes, later dismissed

2023-05-22 03:15 UTC, Luciaw1219 approved these changes

2023-05-22 03:16 UTC, merged